### ISSUE TITLE
about distance loss

### ISSUE THREAD

**Issue by cl886699** [feevos/ceecnet#7]
Hi feevos, should dists multiply 100 to calculate the loss? in chopchop2rec.py, the dists multiplied 100.

**Comment by feevos** [comment]
Hi @cl886699  it is multiplied by 100, in order to create (and store) 100 subdivisions in the range [0,1], in uint8 format - for compression reasons. Within the [dataset __getitem__](https://github.com/feevos/ceecnet/blob/655d4617b5ded8ac0cbf90ed8ce8554ed60c1f1e/src/LVRCDDataset.py#L72) this is fixed where first the uint8 data are made float32, and then divided by 100 so as to bring them in the correct range. 

So you don't need to do anything in the loss function, the provided labels are in the range [0,1] in float32 format, from the dataset class. But please keep in mind, the source code is a demo, to understand what we did in the paper, and adopt to your needs :). 

All the best,
Foivos

**Comment by cl886699** [comment]
thanks, i got it
